account/urls.py
from django.conf.urls import url
from . import views

app_name = 'account'

urlpatterns = [
    url(r'^signup/', views.signup, name='signup'),
    url(r'^login/', views.loginview, name='login'),
    url(r'^logout/', views.logoutview, name='logout'),
]

forum/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from posts import views
#from account import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('account.urls')),
    url(r'^posts/', include('posts.urls')),
    url(r'^sitepages/', include('sitepages.urls')),
    #url(r'^$', views.loginview, name="home"),
    url(r'^$', views.home, name = "home"),
]

posts/urls.py
from django.conf.urls import url
from . import views

app_name = 'posts'

urlpatterns = [
    url(r'^create/', views.create, name='create'),
    url(r'^(?P<pk>[0-9]+)/detail', views.detail, name='detail'),
    url(r'^userposts/', views.userposts, name='userposts'),
    url(r'^delete/(?P<id>\d+)/$', views.delete),
]

sitepages/urls.py
from django.conf.urls import url
from . import views

app_name = 'sitepages'

urlpatterns = [
    url(r'^about/', views.about, name='about'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Welcome to 15-112</title>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  </head>
  <body>

  	<nav class="navbar navbar-inverse">
	  <div class="container">
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#mynav">
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	      <a class="navbar-brand" href="{% url 'home' %}">15-112 Calendar</a>
	    </div>
	    <div class="collapse navbar-collapse" id="mynav">
      		<ul class="nav navbar-nav navbar-right">
      			{% if user.is_authenticated %}   
      			<li><a href="{% url 'sitepages:about' %}">About</a></li>
            <li><a href="#" onclick="document.getElementById('myposts').submit()">My Events</a></li>
      			<li><a href="#" onclick="document.getElementById('logout').submit()">Log Out</a></li>
            <form id="myposts" method="POST" action="{% url 'posts:userposts' %}">
              {% csrf_token %}
            <input type="hidden">
            </form>
      			<form id="logout" method="POST" action="{% url 'account:logout' %}">
      				{% csrf_token %}
      				<input type="hidden">
      			</form>
      			{% else %}
      			<li><a href="{% url 'sitepages:about' %}">About</a></li>
      			<li><a href="{% url 'account:signup' %}">Sign up</a></li>
      			<li><a href="{% url 'account:login' %}">Log In</a></li>
      			{% endif %}
      		</ul>
      	</div>
	  </div>
	</nav>

	<div class="container">
		{% block content %}

		{% endblock %}
	</div>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </body>
</html>