forum/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from posts import views
#from account import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('account.urls')),
    url(r'^posts/', include('posts.urls')),
    url(r'^sitepages/', include('sitepages.urls')),
    #url(r'^$', views.loginview, name="home"),
    url(r'^$', views.home, name = "home"),
]

posts/urls.py
from django.conf.urls import url
from . import views

app_name = 'posts'

urlpatterns = [
    url(r'^create/', views.create, name='create'),
    url(r'^(?P<pk>[0-9]+)/detail', views.detail, name='detail'),
    url(r'^userposts/', views.userposts, name='userposts'),
    url(r'^delete/(?P<id>\d+)/$', views.delete),
]

posts/models.py
from django.db import models
from django.core.exceptions import ValidationError
from django.urls import reverse
from django.contrib.auth.models import User
import datetime
 
class Schedule(models.Model):
    title = models.CharField(max_length=200)
    day = models.DateField()
    start_time = models.TimeField()
    end_time = models.TimeField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    notes = models.TextField(blank=True, null=True)

    def summary(self):
        return self.title[:10]

    class Meta:
        verbose_name = 'Schedule'
        verbose_name_plural = 'Schedule'

    def overlapCheck(self, fixed_start, fixed_end, new_start, new_end):
        overlap = False
        start_sig = new_start.split(':')
        this_start = datetime.time(int(start_sig[0]), int(start_sig[1]), int(start_sig[2]))
        end_sig = new_end.split(':')
        this_end = datetime.time(int(end_sig[0]), int(end_sig[1]), int(end_sig[2]))

        # edge case
        if this_start == fixed_end or this_end == fixed_start:
            overlap = False
        # inner limits
        elif (this_start >= fixed_start and this_start <= fixed_end) or \
            (this_end >= fixed_start and this_end <= fixed_end):
            overlap = True
        # outer limits
        elif this_start <= fixed_start and this_end >= fixed_end:
            overlap = True
        return overlap

    def clean(self):
        if self.end_time <= self.start_time:
            msg = 'Ending time must be after the starting time'
            raise ValidationError(msg)
        user_events = Schedule.objects.filter(author=self.author)
        events = user_events.filter(day=self.day)
        if events.exists():
            for event in events:
                if self.overlapCheck(event.start_time, event.end_time, \
                    self.start_time, self.end_time):
                    raise ValidationError(
                        'There is an overlap with another event: ' \
                        + str(event.title) + ' on ' +\
                        str(event.day) + ', ' + str(event.start_time) \
                        + '-' + str(event.end_time))

posts/forms.py
from django import forms
from django.shortcuts import get_object_or_404
from .models import Schedule
'''
class MyForm(forms.ModelForm):
    class Meta:
        model = Schedule
'''

posts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from .models import Schedule
import datetime
import calendar
from django.urls import reverse
from django.utils.safestring import mark_safe
from .utils import EventCalendar
from django.views.generic import DeleteView
from django.core.exceptions import ValidationError


@login_required
def create(request):
	username, userid = my_view(request)
	if request.method == "POST":
		if request.POST['title'] and request.POST['day'] and \
		request.POST['start_time'] and request.POST['end_time']:
			event = Schedule()
			event.pub_date = timezone.datetime.now()
			event.title = request.POST['title']
			temptitle = request.POST['title']
			event.day = request.POST['day']
			tempday = request.POST['day']
			event.start_time = request.POST['start_time']
			tempst = request.POST['start_time']
			event.end_time = request.POST['end_time']
			tempet = request.POST['end_time']
			event.author = request.user
			event.notes = request.POST['notes']
			try:
			    event.clean()
			    event.save()
			    return redirect('home')
			except ValidationError as e:
				msg = ""
				for i in e:
					msg += i
			    # Display the validation error as error msg to the user.
				return render(request, 'posts/create.html', {'error': msg})
		else:
			return render(request, 'posts/create.html', {'error': 'ERROR: You must include title, day, start time and end time to create an event'})
	else:
		return render(request, 'posts/create.html')

def my_view(request):
    username = None
    if request.user.is_authenticated:
        username = request.user.username
        userid = request.user.id
        return username, userid

@login_required
def home(request, extra_context=None):
    username, userid = my_view(request)
    after_day = request.GET.get('day__gte', None)
    extra_context = extra_context or {}
    if not after_day:
        today = datetime.date.today()
    else:
        try:
            split_after_day = after_day.split('-')
            today = datetime.date(year=int(split_after_day[0]), \
                month=int(split_after_day[1]), day=1)
        except:
            today = datetime.date.today()
    # find last day of previous month
    lDay = datetime.date(year=today.year, month=today.month, day=1) \
            - datetime.timedelta(days=1)
    # get the first day of previous month
    previous_month = datetime.date(year=lDay.year, \
        month=lDay.month, day=1)

    last_day = calendar.monthrange(today.year, today.month)
    # find last day of current month
    next_month = datetime.date(year=today.year, month=today.month, day=last_day[1])
    # goes a single day forward
    next_month = next_month + datetime.timedelta(days=1)
    # find first day of next month
    next_month = datetime.date(year=next_month.year, \
        month=next_month.month, day=1)

    extra_context['previous_month'] =  '?day__gte=' \
        + str(previous_month)
    extra_context['next_month'] = '?day__gte=' + str(next_month)

    # EventCalendar class from utils.py
    schedules = Schedule.objects.filter(author__id=userid)

    cal = EventCalendar(schedules)
    html_calendar = cal.formatmonth(today.year, today.month, withyear=True)
    html_calendar = \
        html_calendar.replace('<td ', '<td  width="200" height="180"')
    extra_context['calendar'] = mark_safe(html_calendar)
    extra_context['username'] = username
    schedules = Schedule.objects.order_by('start_time')
    extra_context['schedules'] = schedules
    return render(request, 'posts/home.html', extra_context) 


	#schedules = Schedule.objects.order_by('start_time')
	#return render(request, 'posts/home.html', {'schedules': schedules}) 

def delete(request, id):
    event = Schedule.objects.filter(pk=id).delete()
    return redirect('home')

def detail(request, pk):
	event = Schedule.objects.get(pk=pk)	    
	username, userid = my_view(request)
	if request.method == "POST":
		if request.POST['title'] and request.POST['day'] and \
		request.POST['start_time'] and request.POST['end_time']:
			new_event = Schedule()
			new_event.title = request.POST['title']
			new_event.day = request.POST['day']
			new_event.start_time = request.POST['start_time']
			new_event.end_time = request.POST['end_time']
			new_event.author = request.user
			new_event.notes = request.POST['notes']
			try:
			    new_event.clean()
			    new_event.save()
			    return delete(request, pk)
			except ValidationError as e:
			    msg = ""
			    for i in e:
			    	msg += i
			    # Display the validation error as error msg to the user.
			    return render(request, 'posts/create.html', {'error': msg})
		else:
			return render(request, 'posts/create.html', {'error': 'ERROR: You must include title, day, start time and end time to create an event'})
	return render(request, 'posts/detail.html', {'event': event})

def userposts(request):
    username, userid = my_view(request)
    org_event = []
    event = Schedule.objects.filter(author__id=userid).order_by('day')
    today = datetime.date.today()
    return render(request, 'posts/userposts.html', {'events': event, 'user': username})

posts/templates/posts/create.html
{% extends 'base.html' %}
{% block content %}
<h1 class="text-center">Create Event</h1>
{% if error %}
<center>
{{ error }}</center>
{% endif %}
<hr>
<form method="POST" action="{% url 'posts:create' %}">
	{% csrf_token %}
	<center><h5>Title:</h5>
	<input type="text" name="title"/>
	<br/>
	<br/>
	<h5>Day:</h5>
	<input type="text" name="day" value="YYYY-MM-DD" />
	<br/>
	<br/>
	<h5>Start Time:</h5>
	<input type="text" name="start_time" value="HH:MM:SS" />
	<br/>
	<br/>
	<h5>End Time:</h5>
	<input type="text" name="end_time" value="HH:MM:SS" />
	<br/>
	<br/>
	<h5>Notes:</h5>
	<input type="text" name="notes"/>
	<br/>
	<br/>
	<input class="btn btn-info" type="submit" value="Create Event">
</center>
</form>
{% endblock %}

posts/templates/posts/detail.html
{% extends 'base.html' %}
{% block content %}
<center>
	<h3 class="text-center">Event Detail</h3>
	<hr>
	<h2>{{ event.title }}
	</h2>
	<h4>scheduled by: {{ event.author }}
		<span class="glyphicon glyphicon-time" aria-hidden="true"></span>
		</h4>
	{% if error %}
	<center>
	{{ error }}</center>
	{% endif %}
<hr>
<form id="edit" method="POST" action="{% url 'posts:detail' event.id %}">
	{% csrf_token %}
	<center><h5>Title:</h5>
	<input type="text" name="title" value="{{ event.title }}" />
	<br/>
	<br/>
	<h5>Day:</h5>
	<input type="text" name="day" value="{{ event.day }}"/>
	<br/>
	<br/>
	<h5>Start Time:</h5>
	<input type="text" name="start_time" value="{{ event.start_time }}"/>
	<br/>
	<br/>
	<h5>End Time:</h5>
	<input type="text" name="end_time" value="{{ event.end_time }}"/>
	<br/>
	<br/>
	<h5>Notes:</h5>
	<input type="text" name="notes" value="{{ event.notes }}"/>
	<br/>
	<br/>
	<input class="btn btn-sm btn-info" type="submit" value="Save Event">
</center>
</form>
	<h4>
		&nbsp; <a href="/posts/delete/{{ event.id }}" class="btn btn-sm btn-danger">Delete Event</a>
	</h4>

</center>
{% endblock %}

posts/templates/posts/home.html
{% extends 'base.html' %}
<br/>
{% block content %}
  <div id="content-main">
          <ul class="object-tools">
                <a href={{ previous_month }} class="btn btn-sm btn-default pull-left">
                    Previous Month
                </a>
                <a href={{ next_month }} class="btn btn-sm btn-default pull-right">
                    Next Month
                </a>
        </ul>
		<h2 class="text-center">{{ username }}'s calendar</h2>
		<hr>
        <center><a href="{% url 'posts:create' %}" class="btn btn-warning"> Create Event</a></center>

        <center><p>{{ calendar }}</p></center>

<br>
<hr>
<!-- 15-112 website embedded is from Carnegie Mellon 15-112 course material -->

<!-- the text editor embedded is from writeurl.com, which is a collaborative real-time online text editor.
WriteURL is owned by Amber Biosciences AB -->

<iframe src="http://www.cs.cmu.edu/~112/schedule.html" width=600px; height=400px;></iframe> 
<iframe src="http://www.writeurl.com/new" width=530px; height=400px;></iframe>

<br>
<br>
{% endblock %}

posts/templates/posts/userposts.html
{% extends 'base.html' %}
{% block content %}
<center>
<h1>All Events by <b><i>{{ user }}</i></b> </h1>
<a href="{% url 'posts:create' %}" class="btn btn-lg btn-info"> Create New Event
 </a>
 <hr>
{% for event in events.all %}
<h3><a href="{% url 'posts:detail' event.id %}">{{ event.title }}</a></h3>
<h4>Date <span class="glyphicon glyphicon-time text-center" aria-hidden="true"></span></h4>
{{ event.day }}
<h4>Start Time:</h4>
 {{ event.start_time }}
<h4>End Time:</h4>
{{ event.end_time }}
<h4>Notes:</h4>
{{ event.notes }}
<br/>

{% endfor %}
</center>
{% endblock %}